classes:
- system.linux.system.repo.mcp.openstack
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.ubuntu
- system.linux.system.repo.glusterfs
- system.linux.system.repo.saltstack.xenial
- service.keepalived.cluster.single
- system.glusterfs.server.cluster
- system.glusterfs.server.volume.salt_pki
- system.salt.control.virt
- system.salt.control.cluster.opencontrail_analytics_cluster
- system.salt.control.cluster.opencontrail_control_cluster
- system.glusterfs.server.volume.glance
- system.glusterfs.server.volume.keystone
- system.salt.control.cluster.openstack_control_cluster
- system.salt.control.cluster.openstack_proxy_cluster
- system.salt.control.cluster.openstack_database_cluster
- system.salt.control.cluster.openstack_message_queue_cluster
- system.salt.control.cluster.openstack_telemetry_cluster
- cluster.mcp-contrail.infra
parameters:
  _param:
    cluster_vip_address: ${_param:infra_kvm_address}
    cluster_node01_address: ${_param:infra_kvm_node01_address}
    cluster_node02_address: ${_param:infra_kvm_node02_address}
    cluster_node03_address: ${_param:infra_kvm_node03_address}
    keepalived_vip_interface: br_ctl
    keepalived_vip_virtual_router_id: 69
    deploy_nic: ens3
    primary_first_nic: ens4
    primary_second_nic: ens5
  salt:
    control:
      size: #RAM 4096,8192,16384,32768,65536
      ##Default production sizing
        openstack.control:
          cpu: 2
          ram: 6146
          disk_profile: small
          net_profile: default
        openstack.database:
          cpu: 2
          ram: 4096
          disk_profile: large
          net_profile: default
        openstack.message_queue:
          cpu: 1
          ram: 4096
          disk_profile: small
          net_profile: default
        openstack.telemetry:
          cpu: 1
          ram: 4096
          disk_profile: xxlarge
          net_profile: default
        openstack.proxy:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        opencontrail.control:
          cpu: 2
          ram: 7170
          disk_profile: small
          net_profile: default
        opencontrail.analytics:
          cpu: 1
          ram: 4096
          disk_profile: large
          net_profile: default
        stacklight.log:
          cpu: 1
          ram: 2048
          disk_profile: xxlarge
          net_profile: default
        stacklight.server:
          cpu: 1
          ram: 2048
          disk_profile: small
          net_profile: default
        stacklight.telemetry:
          cpu: 1
          ram: 2048
          disk_profile: xxlarge
          net_profile: default
      cluster:
        internal:
          node:
            mdb01:
              image: ${_param:salt_control_xenial_image}
            mdb02:
              image: ${_param:salt_control_xenial_image}
            mdb03:
              image: ${_param:salt_control_xenial_image}
            ctl01:
              image: ${_param:salt_control_xenial_image}
            ctl02:
              image: ${_param:salt_control_xenial_image}
            ctl03:
              image: ${_param:salt_control_xenial_image}
            dbs01:
              image: ${_param:salt_control_xenial_image}
            dbs02:
              image: ${_param:salt_control_xenial_image}
            dbs03:
              image: ${_param:salt_control_xenial_image}
            msg01:
              image: ${_param:salt_control_xenial_image}
            msg02:
              image: ${_param:salt_control_xenial_image}
            msg03:
              image: ${_param:salt_control_xenial_image}
            prx01:
              image: ${_param:salt_control_xenial_image}
            prx02:
              image: ${_param:salt_control_xenial_image}
  virt:
    nic:
      default:
        ens3:
          bridge: br_mgm
        ens4:
          bridge: br_ctl
  linux:
    network:
      interface:
        ens3:
          enabled: true
          type: eth
          proto: manual
          name: ${_param:deploy_nic}
          mtu: 1450
        ens4:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_first_nic}
          mtu: 1450
        ens5:
          enabled: true
          type: slave
          proto: manual
          name: ${_param:primary_second_nic}
          mtu: 1450
        br_mgm:
          enabled: true
          proto: static
          type: bridge
          address: ${_param:deploy_address}
          netmask: ${_param:deploy_network_netmask}
          gateway: ${_param:deploy_network_gateway}
          name_servers:
          - ${_param:dns_server01}
          - ${_param:dns_server02}
          use_interfaces:
          - ${_param:deploy_nic}
          mtu: 1450
        br_ctl:
          enabled: true
          type: bridge
          proto: static
          address: ${_param:single_address}
          netmask: ${_param:control_network_netmask}
          use_interfaces:
          - ${_param:primary_first_nic}
          mtu: 1450
  #   system:
  #     package:
  #       linux-image-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39-generic:
  #         version: latest
  #       linux-image-extra-4.8.0-39-generic:
  #         version: latest
  #       linux-headers-4.8.0-39:
  #         version: latest
  #     user:
  #       root:
  #         enabled: true
  #         name: root
  #         home: /root
  #         # Password is cloudlab, comment out, configure your SSH key bellow
  #         # and disable password auth
  #         password: $6$0Qqj.6l.$T9k9Onm9pIDo6ULABVBRNogyizG.9CnwQ4bvI4xH.AWeIGHbLyFU87ejMTtKvAAyd3dncRYbeUV.VbnXJU2u./
